[client]
rpc_port = 8432
admin_rpc_host = "127.0.0.1"
admin_rpc_port = 8434
admin_rpc_bearer_token = "dev-only-change-me"
l2_blocks_fetch_limit = 1_000
datadir = "/path/to/data/directory"
# sequencer_key = "/path/to/data/directory/"
# sequencer_bitcoin_address = ""
db_retry_count = 5
max_headers_range = 5_000

[logging]
metrics_port = 9615

[bitcoind]
rpc_url = "localhost:18332"
rpc_user = "alpen"
rpc_password = "alpen"
network = "regtest"

[sync]
l1_follow_distance = 6
client_checkpoint_interval = 10

[btcio.reader]
client_poll_dur_ms = 200

[btcio.writer]
write_poll_dur_ms = 200
fee_policy = "mempool"
# Required when fee_policy = "mempool"
# mempool_base_url = "https://mempool.space"
# Optional when fee_policy = "mempool"
# mempool_fee_policy = "economy"
# Optional when fee_policy = "mempool"
# mempool_fallback_conf_target = 6
# Optional when fee_policy = "bitcoind"
# bitcoind_conf_target = 6
# Required when fee_policy = "fixed"
# fixed_fee_rate = 5
mempool_base_url = "https://mempool.space"
reveal_amount = 100

[exec.reth]
# reth {authrpc.address}:{authrpc.port}
rpc_url = "localhost:8551"
# reth authrpc.jwtsecret path
secret = "/path/to/jwt.hex"
