[package]
name = "strata-ol-stf"
version = "0.1.0"
edition = "2024"

[dependencies]
ssz_primitives = { workspace = true, optional = true }
ssz_types = { workspace = true, optional = true }
strata-acct-types.workspace = true
strata-asm-common.workspace = true
strata-asm-logs.workspace = true
strata-bridge-params.workspace = true
strata-codec.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-merkle.workspace = true
strata-msg-fmt.workspace = true
strata-ol-bridge-types.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-da.workspace = true
strata-ol-msg-types.workspace = true
strata-ol-params = { workspace = true, optional = true }
strata-ol-state-support-types = { workspace = true, optional = true }
strata-ol-state-types.workspace = true
strata-predicate.workspace = true
strata-snark-acct-sys.workspace = true
strata-snark-acct-types.workspace = true

tracing.workspace = true

[dev-dependencies]
ssz_primitives.workspace = true
ssz_types.workspace = true
strata-ol-params.workspace = true
strata-ol-state-support-types.workspace = true
strata-predicate.workspace = true

[lints]
workspace = true

[features]
test-utils = [
  "dep:ssz_primitives",
  "dep:ssz_types",
  "dep:strata-ol-params",
  "dep:strata-ol-state-support-types",
]
