#!/usr/bin/env bash
set -euo pipefail

# Generate minimal keys and env for the EEST Docker stack.
#
# Usage:
#   cd docker && ./init-eest-keys.sh
#
# Outputs:
#   .env.alpen                              env file for docker-compose-eest.yml
#   configs/alpen-client/jwt.hex            engine JWT secret
#   configs/alpen-client/seq-p2p.hex        P2P secret key
#   configs/alpen-client/sequencer-schnorr.hex
#                                            sequencer Schnorr secret key

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/configs/alpen-client"

PYTHON=""
for candidate in python3 python3.12 python3.11 python3.10 python; do
    if command -v "${candidate}" >/dev/null 2>&1 && "${candidate}" -c "import coincurve" >/dev/null 2>&1; then
        PYTHON="${candidate}"
        break
    fi
done

if [ -z "${PYTHON}" ]; then
    echo "error: no python with 'coincurve' found. install: pip install coincurve" >&2
    exit 1
fi

generate_secret_key() {
    od -An -tx1 -N32 /dev/urandom | tr -d ' \n'
}

derive_schnorr_pubkey() {
    local privkey_hex="$1"
    echo -n "${privkey_hex}" | "${PYTHON}" -c '
import coincurve
import sys

private_key = bytes.fromhex(sys.stdin.read())
public_key = coincurve.PublicKey.from_secret(private_key)
sys.stdout.write(public_key.format(compressed=True)[1:].hex())
'
}

generate_key_file() {
    local filepath="$1"
    if [ -f "${filepath}" ]; then
        echo "exists: ${filepath}"
        return
    fi

    generate_secret_key > "${filepath}"
    echo "generated: ${filepath}"
}

mkdir -p "${OUTPUT_DIR}"

SCHNORR_KEY="${OUTPUT_DIR}/sequencer-schnorr.hex"
generate_key_file "${SCHNORR_KEY}"
SCHNORR_PRIVKEY="$(cat "${SCHNORR_KEY}")"
SCHNORR_PUBKEY="$(derive_schnorr_pubkey "${SCHNORR_PRIVKEY}")"

SEQ_P2P_KEY="${OUTPUT_DIR}/seq-p2p.hex"
generate_key_file "${SEQ_P2P_KEY}"

JWT_KEY="${OUTPUT_DIR}/jwt.hex"
generate_key_file "${JWT_KEY}"

ENV_FILE="${SCRIPT_DIR}/.env.alpen"

cat > "${ENV_FILE}" <<EOF
# Generated by init-eest-keys.sh -- do not edit.

SEQUENCER_PRIVATE_KEY=${SCHNORR_PRIVKEY}
SEQUENCER_PUBKEY=${SCHNORR_PUBKEY}

CHAIN_SPEC=dev

EE_DA_MAGIC_BYTES=ALPN
L1_REORG_SAFE_DEPTH=1
GENESIS_L1_HEIGHT=101
BATCH_SEALING_BLOCK_COUNT=5

BITCOIND_RPC_USER=rpcuser
BITCOIND_RPC_PASSWORD=rpcpassword
BITCOIND_RPC_PORT=18443

RUST_LOG=info
EOF

echo "wrote ${ENV_FILE}"
echo "sequencer pubkey: ${SCHNORR_PUBKEY}"
