"""EE predicate transition functional test.

Verifies that a sequence of admin `PredicateUpdate`s rotates the Alpen snark
account's `update_vk` through each target predicate in OL state.
"""

import logging
from pathlib import Path

import flexitest

from common.base_test import BaseTest
from common.config.constants import ALPEN_ACCOUNT_ID, ServiceType
from common.services.alpen_client import AlpenClientService
from common.services.bitcoin import BitcoinService
from common.services.strata import StrataService
from common.test_cli import create_ee_predicate_update
from common.wait import wait_until_with_value

logger = logging.getLogger(__name__)

INITIAL_BLOCKS = 5
POST_ADMIN_UPDATE_L1_BLOCKS = 5
PREDICATE_SETTLE_TIMEOUT_SECONDS = 120

# Dummy condition bytes for predicates that require them. Admin updates do not
# validate the condition format, so any bytes round-trip through OL state.
SP1_CONDITION_HEX = "11" * 32
BIP340_CONDITION_HEX = "22" * 32

# Initial Alpen account predicate matches `EeAcctProgram::test_predicate_key()`
# (deterministic test SK = [0x02; 32] in strata_proofimpl_alpen_acct).
INITIAL_ACCT_PREDICATE = (
    "Bip340Schnorr:4d4b6cd1361032ca9bd2aeb9d900aa4d45d9ead80ac9423374c451a7254d0766"
)

PREDICATE_TRANSITIONS = [
    "NeverAccept",
    "AlwaysAccept",
    f"Sp1Groth16:{SP1_CONDITION_HEX}",
    f"Bip340Schnorr:{BIP340_CONDITION_HEX}",
]


@flexitest.register
class TestEePredicateTransition(BaseTest):
    def __init__(self, ctx: flexitest.InitContext):
        ctx.set_env("el_ol_ee_predicate_transition")

    def main(self, ctx):
        alpen_seq: AlpenClientService = self.get_service(ServiceType.AlpenSequencer)
        strata_seq: StrataService = self.get_service(ServiceType.Strata)
        bitcoin: BitcoinService = self.get_service(ServiceType.Bitcoin)
        btc_rpc = bitcoin.create_rpc()

        strata_rpc = strata_seq.wait_for_rpc_ready(timeout=30)
        strata_seq.wait_for_account_genesis_epoch_commitment(
            ALPEN_ACCOUNT_ID,
            rpc=strata_rpc,
            timeout=30,
        )
        alpen_seq.wait_for_block(INITIAL_BLOCKS, timeout=120)

        # Read the single operator/admin xpriv generated by datatool.
        admin_key_path = Path(strata_seq.props["datadir"]) / "bridge-operator_keys"
        if not admin_key_path.exists():
            raise AssertionError(f"admin key file not found: {admin_key_path}")
        admin_xpriv = admin_key_path.read_text().strip()
        if not admin_xpriv:
            raise AssertionError(f"admin key file is empty: {admin_key_path}")

        btc_url = bitcoin.props["rpc_url"]
        btc_user = bitcoin.props["rpc_user"]
        btc_password = bitcoin.props["rpc_password"]
        mine_addr = btc_rpc.proxy.getnewaddress()

        def fetch_update_vk_and_mine() -> str:
            btc_rpc.proxy.generatetoaddress(1, mine_addr)
            return strata_rpc.strata_getSnarkAccountState(ALPEN_ACCOUNT_ID, "latest")["update_vk"]

        initial_vk = strata_rpc.strata_getSnarkAccountState(ALPEN_ACCOUNT_ID, "latest")["update_vk"]
        if initial_vk != INITIAL_ACCT_PREDICATE:
            raise AssertionError(
                f"expected initial update_vk to be {INITIAL_ACCT_PREDICATE!r}, got {initial_vk!r}"
            )

        for seq_no, target in enumerate(PREDICATE_TRANSITIONS, start=1):
            result = create_ee_predicate_update(
                seq_no=seq_no,
                predicate=target,
                admin_xpriv=admin_xpriv,
                btc_url=btc_url,
                btc_user=btc_user,
                btc_password=btc_password,
            )
            logger.info("Applied %s update (seq %d): %s", target, seq_no, result)

            btc_rpc.proxy.generatetoaddress(POST_ADMIN_UPDATE_L1_BLOCKS, mine_addr)

            wait_until_with_value(
                fetch_update_vk_and_mine,
                lambda vk, target=target: vk == target,
                error_with=f"update_vk did not transition to {target} in OL state",
                timeout=PREDICATE_SETTLE_TIMEOUT_SECONDS,
            )
            logger.info("update_vk transitioned to %s", target)

        return True
