[client]
rpc_host = "0.0.0.0"
rpc_port = 8432
admin_rpc_host = "127.0.0.1"
admin_rpc_port = 8434
admin_rpc_bearer_token = "dev-only-change-me"
l2_blocks_fetch_limit = 1_000
datadir = "data"
db_retry_count = 5
# sequencer_rpc = "ws://strata-nodes-client-svc:8432"
sync_endpoint = "ws://strata-client-strata-nodes-refactor-client-svc:8432"

[logging]
metrics_host = "0.0.0.0"
metrics_port = 9615

[bitcoind]
rpc_url = "http://bitcoind:38332"
rpc_user = "rpcuser"
rpc_password = "rpcpassword"
network = "signet"

[sync]
l1_follow_distance = 6
client_checkpoint_interval = 20

[btcio.reader]
client_poll_dur_ms = 10_000

[btcio.writer]
write_poll_dur_ms = 10_000
fee_policy = "mempool"
# Required when fee_policy = "mempool"
# mempool_base_url = "https://mempool.space/signet"
# Optional when fee_policy = "mempool"
# mempool_fee_policy = "economy"
# Optional when fee_policy = "mempool"
# mempool_fallback_conf_target = 6
# Optional when fee_policy = "bitcoind"
# bitcoind_conf_target = 6
# Required when fee_policy = "fixed"
# fixed_fee_rate = 5
mempool_base_url = "https://mempool.space/signet"
reveal_amount = 100
bundle_interval_ms = 1_000

[btcio.broadcaster]
poll_interval_ms = 1_000


[exec.reth]
rpc_url = "rethfn1-strata-nodes-refactor-reth-fn-1-svc:8551"
secret = "configs/jwt.fn.hex"

[relayer]
refresh_interval = 10
stale_duration = 10
relay_misc = true

[prover]
backend = "sp1"
workers = 1
